### ISSUE TITLE
WP Update and Security Issues

### ISSUE THREAD

**Issue by tkarim** [jlauters/florissant-wordpress#4]
From CU OIT: 
You're getting this email because you are a technical contact for
florissantdatabase.colorado.edu. If you could please pass it on to the
necessary parties that would be much appreciated.

A recent security scan has revealed that the Wordpress site on
florissantdatabase is vulnerable to XML-RPC Pingback abuse, which can be used to start DDOS
attacks. It can be disabled pretty quickly and easily by installing a
plugin or disabling it via your theme's functions.php. See this link for
more details on how to fix this:

https://cm.org.uk/wordpress/how-to-protect-your-wordpress-blog-from-xml-rp
c-pingback-abuse/

Please have you or whomever solves this email me when the problem is
taken care of.

Thanks,
-- Will Drach
OIT SIS Unix Team
widr1225@colorado.edu

**Comment by jlauters** [comment]
Updated WP 4.2.2
