### ISSUE TITLE
WP Update and Security Issues

### ISSUE THREAD

**Issue by tkarim** [jlauters/florissant-wordpress#5]
Also from CU OIT:

I looked back through the security scan for florissantdatabase and
also realized that the WordPress installation needs to be updated. This
is usually a fairly quick process and can be done by following the guide
below: https://codex.wordpress.org/Updating_WordPress#One-click_Update

The older versions of WordPress (it looks like florissantdatabase is
using a version <3.8.2) have lots of security vulnerabilities that were
fixed in later versions.

If you have any questions or concerns, let me know.

Thanks,
-- Will Drach
OIT SIS Unix Team
widr1225@colorado.edu

**Comment by jlauters** [comment]
Updated WP 4.2.2
